# CUSTOMER QUERY POINTER
CUSTOMERQUERY_CUSTOMER_ID = 0
CUSTOMERQUERY_CUSTOMER_ADDRESS = 1
CUSTOMERQUERY_CUSTOMER_CONTACT_PERSON = 2
CUSTOMERQUERY_CUSTOMER_NAME = 3
CUSTOMERQUERY_CUSTOMER_NO_TELP = 4
CUSTOMERQUERY_CUSTOMER_DAERAH = 5
CUSTOMERQUERY_MASTER_LIST_NAME = 6
CUSTOMERQUERY_SALES_ORDER_ID = 7
CUSTOMERQUERY_SALES_ORDER_DATE = 8
CUSTOMERQUERY_SALES_ORDER_DELIVERY_DATE = 9
CUSTOMERQUERY_SALES_ORDER_INVOICE_ID = 10
CUSTOMERQUERY_SALES_ORDER_INVOICE_DATE = 11
CUSTOMERQUERY_SALES_ORDER_INVOICE_DUE_DATE = 12
CUSTOMERQUERY_SALES_ORDER_INVOICE_DATE_COMPLETED = 13
CUSTOMERQUERY_SALES_ORDER_TOTAL = 14
CUSTOMERQUERY_SALES_ORDER_STATUS_ID = 15
CUSTOMERQUERY_APPROVAL_STATUS_NAME = 16
CUSTOMERQUERY_PAYMENT_METHOD_NAME = 17
CUSTOMERQUERY_SALES_ORDER_INVOICE_INVOICE_NUMBER = 18
CUSTOMERQUERY_CUSTOMER_REFERENCE_CODE = 19
CUSTOMERQUERY_DELIVERY_DATE = 20
CUSTOMERQUERY_DELIVERY_STATUS = 21
CUSTOMERQUERY_DRIVER_NAME = 22
CUSTOMERQUERY_TOTAL_PAYMENT_AMOUNT = 23

# ITEM QUERY
ITEMQUERY_SALES_ORDER_DETAIL_SALES_ORDER_ID = 0
ITEMQUERY_SALES_ORDER_DETAIL_ID = 1
ITEMQUERY_ITEM_NAME = 2
ITEMQUERY_SALES_ORDER_DETAIL_QUANTITY = 3
ITEMQUERY_SALES_ORDER_DETAIL_PRICE = 4

# DEBT QUERY
DEBTQUERY_CUSTOMER_ID = 0
DEBTQUERY_SALES_ORDER_ID = 1
DEBTQUERY_SALES_ORDER_DATE = 2
DEBTQUERY_SALES_ORDER_DELIVERY_DATE = 3
DEBTQUERY_SALES_ORDER_INVOICE_ID = 4
DEBTQUERY_SALES_ORDER_INVOICE_DATE = 5
DEBTQUERY_SALES_ORDER_INVOICE_DUE_DATE = 6
DEBTQUERY_SALES_ORDER_INVOICE_TOTAL = 7
DEBTQUERY_PAYMENT_METHOD_NAME = 8
DEBTQUERY_SALES_ORDER_INVOICE_INVOICE_NUMBER = 9
DEBTQUERY_TOTAL_PAYMENT_AMOUNT = 10
DEBTQUERY_DEBT = 11

# PAYMENT DETAILS QUERY
PAYMENTDETAILSQUERY_CUSTOMER_ID = 0
PAYMENTDETAILSQUERY_SALES_ORDER_ID = 1
PAYMENTDETAILSQUERY_SALES_ORDER_INVOICE_ID = 2
PAYMENTDETAILSQUERY_SALES_ORDER_INVOICE_DATE = 3
PAYMENTDETAILSQUERY_SALES_ORDER_PAYMENT_DATE = 4
PAYMENTDETAILSQUERY_SALES_ORDER_PAYMENT_AMOUNT = 5
PAYMENTDETAILSQUERY_SALES_ORDER_PAYMENT_DESCRIPTION = 6
PAYMENTDETAILSQUERY_TOTAL_PAYMENT_AMOUNT = 7

# INACTIVE CUSTOMER QUERY POINTER
INACTIVECUSTOMERQUERY_CUSTOMER_ID = 0
INACTIVECUSTOMERQUERY_CUSTOMER_ADDRESS = 1
INACTIVECUSTOMERQUERY_CUSTOMER_CONTACT_PERSON = 2
INACTIVECUSTOMERQUERY_CUSTOMER_NAME = 3
INACTIVECUSTOMERQUERY_CUSTOMER_NO_TELP = 4
INACTIVECUSTOMERQUERY_CUSTOMER_DAERAH = 5
INACTIVECUSTOMERQUERY_MASTER_LIST_NAME = 6
INACTIVECUSTOMERQUERY_CUSTOMER_REFERENCE_CODE = 7